name: open_alex_api
description: A Dart API client for the Open Alex API.
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  http: ^0.13.4
  json_annotation: ^4.5.0

dev_dependencies:
  coverage: ^1.3.2
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  test: ^1.21.2
